@startuml cicd
title CI/CD Pipeline for a Node Application

participant "Developer\nlocal branch" as dev
participant "Github\nmain branch" as repo
participant "Github\nActions" as act
participant "Deploy\nStaging" as stage
participant "Container\nRegistry" as store
participant "Production\nServer" as prod
participant "Slack\nTeam" as team

== Pipeline Trigger ==
dev -> repo : Open PR or\npush to main
repo -> act: Trigger CI/CD pipeline
== Inital linting ==
act -> act : Lint changes &\ncheck for quality
group  #ff7474 Code fails linter
    act -> repo : Block merge\nand close PR
    act -> dev : Notify developer w/ error message
end
== Setup testing environment once ==
act -> act : Build node\ntesting container
act -> act : Install npm deps
act -> act : Transpile/bundle\nbranch
== Automated quality checks / test suite ==
act -> act : Unit testing
act -> act : Integration testing
group  #ff7474 Any test fails
    act -> repo : Block merge\nand close PR
    act -> team : Notify team of failed push with link to logs
end
group #54b173 All tests pass
    act -> repo : Allow merge\nand close PR
    act -> stage : Push to staging
end
== Build and deploy ==
stage -> store : Build prod\ncontainers
stage -> stage : Manual checks\n(if applicable)
stage -> prod : Deploy changes
act -> team : Notify team of successful deployment
@enduml